services:

  gholi-db:
    image: postgres:14.8
    container_name: gholi-db-dev
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}        
      POSTGRES_PASSWORD: ${PG_PASSWORD}    
      POSTGRES_MULTIPLE_DATABASES: ${PG_MULTIPLE_DATABASES}  
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - gholi-db-volume:/var/lib/postgresql/data:rw
      - ./scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh:ro

  gholi-redis:
      image: redis/redis-stack:7.2.0-v3
      container_name: gholi-redis-dev
      volumes:
        - gholi-redis-volume:/data
      ports:
        - "6380:6379"
        - "8020:8001"
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 3s
        retries: 5
      restart: always

  gholi-nats:
    image: nats:2.9-alpine
    container_name: gholi-nats-server
    command: [
      "-js",          
      "--store_dir",  
      "/data"
    ]
    ports:
      - "4222:4222"   
    volumes:
      - gholi-nats_data:/data

  gholi-promtail:
    image: grafana/promtail:latest
    container_name: gholi-promtail-dev
    restart: always
    volumes:
      - ./Logs:/var/log/my-service
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    depends_on:
      - gholi-loki 

  gholi-loki:
    image: grafana/loki:latest
    container_name: gholi-loki-dev
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - gholi-loki-data:/data
    command: -config.file=/etc/loki/local-config.yaml
   
  gholi-grafana:
    image: grafana/grafana:latest
    container_name: gholi-grafana-dev
    restart: always
    ports:
      - "3500:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - gholi-loki
    

volumes:
  gholi-db-volume:
  gholi-redis-volume:
  gholi-nats_data:
  gholi-loki-data:

