// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v5.29.2
// source: staff.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StaffType int32

const (
	StaffType_HOTEL_UNKNOWN      StaffType = 0
	StaffType_HOTEL_MANAGER      StaffType = 1
	StaffType_HOTEL_RECEPTIONIST StaffType = 2
	StaffType_HOTEL_CLEANER      StaffType = 3
	StaffType_HOTEL_SECURITY     StaffType = 4
)

// Enum value maps for StaffType.
var (
	StaffType_name = map[int32]string{
		0: "HOTEL_UNKNOWN",
		1: "HOTEL_MANAGER",
		2: "HOTEL_RECEPTIONIST",
		3: "HOTEL_CLEANER",
		4: "HOTEL_SECURITY",
	}
	StaffType_value = map[string]int32{
		"HOTEL_UNKNOWN":      0,
		"HOTEL_MANAGER":      1,
		"HOTEL_RECEPTIONIST": 2,
		"HOTEL_CLEANER":      3,
		"HOTEL_SECURITY":     4,
	}
)

func (x StaffType) Enum() *StaffType {
	p := new(StaffType)
	*p = x
	return p
}

func (x StaffType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StaffType) Descriptor() protoreflect.EnumDescriptor {
	return file_staff_proto_enumTypes[0].Descriptor()
}

func (StaffType) Type() protoreflect.EnumType {
	return &file_staff_proto_enumTypes[0]
}

func (x StaffType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StaffType.Descriptor instead.
func (StaffType) EnumDescriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{0}
}

type StaffCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StaffType     StaffType              `protobuf:"varint,2,opt,name=staffType,proto3,enum=StaffType" json:"staffType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffCreateRequest) Reset() {
	*x = StaffCreateRequest{}
	mi := &file_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffCreateRequest) ProtoMessage() {}

func (x *StaffCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffCreateRequest.ProtoReflect.Descriptor instead.
func (*StaffCreateRequest) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{0}
}

func (x *StaffCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffCreateRequest) GetStaffType() StaffType {
	if x != nil {
		return x.StaffType
	}
	return StaffType_HOTEL_UNKNOWN
}

type StaffCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staffId,proto3" json:"staffId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffCreateResponse) Reset() {
	*x = StaffCreateResponse{}
	mi := &file_staff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffCreateResponse) ProtoMessage() {}

func (x *StaffCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffCreateResponse.ProtoReflect.Descriptor instead.
func (*StaffCreateResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{1}
}

func (x *StaffCreateResponse) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type GetAllStaffsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staffs        []*Staff               `protobuf:"bytes,1,rep,name=staffs,proto3" json:"staffs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllStaffsResponse) Reset() {
	*x = GetAllStaffsResponse{}
	mi := &file_staff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStaffsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStaffsResponse) ProtoMessage() {}

func (x *GetAllStaffsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStaffsResponse.ProtoReflect.Descriptor instead.
func (*GetAllStaffsResponse) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllStaffsResponse) GetStaffs() []*Staff {
	if x != nil {
		return x.Staffs
	}
	return nil
}

type Staff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StaffType     StaffType              `protobuf:"varint,3,opt,name=staffType,proto3,enum=StaffType" json:"staffType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Staff) Reset() {
	*x = Staff{}
	mi := &file_staff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Staff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staff) ProtoMessage() {}

func (x *Staff) ProtoReflect() protoreflect.Message {
	mi := &file_staff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staff.ProtoReflect.Descriptor instead.
func (*Staff) Descriptor() ([]byte, []int) {
	return file_staff_proto_rawDescGZIP(), []int{3}
}

func (x *Staff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Staff) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Staff) GetStaffType() StaffType {
	if x != nil {
		return x.StaffType
	}
	return StaffType_HOTEL_UNKNOWN
}

var File_staff_proto protoreflect.FileDescriptor

var file_staff_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x61, 0x66, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x52, 0x0a,
	0x12, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x73, 0x74, 0x61, 0x66, 0x66, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x2f, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x66, 0x66, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x61, 0x66,
	0x66, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x49, 0x64, 0x22, 0x36, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x66,
	0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x66, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x52, 0x06, 0x73, 0x74, 0x61, 0x66, 0x66, 0x73, 0x22, 0x55, 0x0a, 0x05, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x66, 0x66,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x53, 0x74, 0x61,
	0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x73, 0x74, 0x61, 0x66, 0x66, 0x54, 0x79, 0x70,
	0x65, 0x2a, 0x70, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11,
	0x0a, 0x0d, 0x48, 0x4f, 0x54, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x11, 0x0a, 0x0d, 0x48, 0x4f, 0x54, 0x45, 0x4c, 0x5f, 0x4d, 0x41, 0x4e, 0x41, 0x47,
	0x45, 0x52, 0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x48, 0x4f, 0x54, 0x45, 0x4c, 0x5f, 0x52, 0x45,
	0x43, 0x45, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x49, 0x53, 0x54, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d,
	0x48, 0x4f, 0x54, 0x45, 0x4c, 0x5f, 0x43, 0x4c, 0x45, 0x41, 0x4e, 0x45, 0x52, 0x10, 0x03, 0x12,
	0x12, 0x0a, 0x0e, 0x48, 0x4f, 0x54, 0x45, 0x4c, 0x5f, 0x53, 0x45, 0x43, 0x55, 0x52, 0x49, 0x54,
	0x59, 0x10, 0x04, 0x42, 0x18, 0x5a, 0x16, 0x67, 0x68, 0x6f, 0x6c, 0x69, 0x2d, 0x66, 0x6c, 0x79,
	0x2d, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_staff_proto_rawDescOnce sync.Once
	file_staff_proto_rawDescData = file_staff_proto_rawDesc
)

func file_staff_proto_rawDescGZIP() []byte {
	file_staff_proto_rawDescOnce.Do(func() {
		file_staff_proto_rawDescData = protoimpl.X.CompressGZIP(file_staff_proto_rawDescData)
	})
	return file_staff_proto_rawDescData
}

var file_staff_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_staff_proto_goTypes = []any{
	(StaffType)(0),               // 0: StaffType
	(*StaffCreateRequest)(nil),   // 1: StaffCreateRequest
	(*StaffCreateResponse)(nil),  // 2: StaffCreateResponse
	(*GetAllStaffsResponse)(nil), // 3: GetAllStaffsResponse
	(*Staff)(nil),                // 4: Staff
}
var file_staff_proto_depIdxs = []int32{
	0, // 0: StaffCreateRequest.staffType:type_name -> StaffType
	4, // 1: GetAllStaffsResponse.staffs:type_name -> Staff
	0, // 2: Staff.staffType:type_name -> StaffType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_staff_proto_init() }
func file_staff_proto_init() {
	if File_staff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_staff_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_staff_proto_goTypes,
		DependencyIndexes: file_staff_proto_depIdxs,
		EnumInfos:         file_staff_proto_enumTypes,
		MessageInfos:      file_staff_proto_msgTypes,
	}.Build()
	File_staff_proto = out.File
	file_staff_proto_rawDesc = nil
	file_staff_proto_goTypes = nil
	file_staff_proto_depIdxs = nil
}
